project:
  type: website

website:
  title: "today"
  navbar:
    left:
      - href: "Simple Site.qmd"
        text: "Shinylive R"
      - href: "Simple Site2.qmd"
        text: "Shinylive Python"

format:
  html:
    theme: superhero
    css: styles.css
    toc: true